# TRRank Configuration

# Language settings (zh_cn or en)
language: zh_cn

# Rank configuration
ranks:
  admin:
    display: "§l§c[Admin]"
    cost: 114514
  player:
    display: "§l§7[Player]"
    cost: 0
  vip:
    display: "§l§a[Vip]"
    cost: 7
  svip:
    display: "§l§6[Svip]"
    cost: 14
  svip_plus:
    display: "§l§e[Svip++]"
    cost: 30
